spring.application.name=Gestor-Productos
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.config.import=optional:file:.secrets.properties

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/tiendas}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha